// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

package com.expedia.www.packagefinder.database.user;

public final class UserInfoProtos {
  private UserInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string origin = 2;</code>
     */
    java.lang.String getOrigin();
    /**
     * <code>optional string origin = 2;</code>
     */
    com.google.protobuf.ByteString
        getOriginBytes();

    /**
     * <code>optional float minBudget = 3;</code>
     */
    float getMinBudget();

    /**
     * <code>optional float maxBudget = 4;</code>
     */
    float getMaxBudget();

    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    boolean hasPrefMatrix();
    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getPrefMatrix();
    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder getPrefMatrixOrBuilder();
  }
  /**
   * Protobuf type {@code user.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:user.UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      userId_ = "";
      origin_ = "";
      minBudget_ = 0F;
      maxBudget_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              origin_ = s;
              break;
            }
            case 29: {

              minBudget_ = input.readFloat();
              break;
            }
            case 37: {

              maxBudget_ = input.readFloat();
              break;
            }
            case 42: {
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder subBuilder = null;
              if (prefMatrix_ != null) {
                subBuilder = prefMatrix_.toBuilder();
              }
              prefMatrix_ = input.readMessage(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prefMatrix_);
                prefMatrix_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.class, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object origin_;
    /**
     * <code>optional string origin = 2;</code>
     */
    public java.lang.String getOrigin() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origin_ = s;
        return s;
      }
    }
    /**
     * <code>optional string origin = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      java.lang.Object ref = origin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MINBUDGET_FIELD_NUMBER = 3;
    private float minBudget_;
    /**
     * <code>optional float minBudget = 3;</code>
     */
    public float getMinBudget() {
      return minBudget_;
    }

    public static final int MAXBUDGET_FIELD_NUMBER = 4;
    private float maxBudget_;
    /**
     * <code>optional float maxBudget = 4;</code>
     */
    public float getMaxBudget() {
      return maxBudget_;
    }

    public static final int PREFMATRIX_FIELD_NUMBER = 5;
    private com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref prefMatrix_;
    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    public boolean hasPrefMatrix() {
      return prefMatrix_ != null;
    }
    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getPrefMatrix() {
      return prefMatrix_ == null ? com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.getDefaultInstance() : prefMatrix_;
    }
    /**
     * <code>optional .user.UserPref prefMatrix = 5;</code>
     */
    public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder getPrefMatrixOrBuilder() {
      return getPrefMatrix();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
      }
      if (!getOriginBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, origin_);
      }
      if (minBudget_ != 0F) {
        output.writeFloat(3, minBudget_);
      }
      if (maxBudget_ != 0F) {
        output.writeFloat(4, maxBudget_);
      }
      if (prefMatrix_ != null) {
        output.writeMessage(5, getPrefMatrix());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
      }
      if (!getOriginBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, origin_);
      }
      if (minBudget_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, minBudget_);
      }
      if (maxBudget_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, maxBudget_);
      }
      if (prefMatrix_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPrefMatrix());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserInfo)
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.class, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.Builder.class);
      }

      // Construct using com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        origin_ = "";

        minBudget_ = 0F;

        maxBudget_ = 0F;

        if (prefMatrixBuilder_ == null) {
          prefMatrix_ = null;
        } else {
          prefMatrix_ = null;
          prefMatrixBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserInfo_descriptor;
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo getDefaultInstanceForType() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.getDefaultInstance();
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo build() {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo buildPartial() {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo result = new com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo(this);
        result.userId_ = userId_;
        result.origin_ = origin_;
        result.minBudget_ = minBudget_;
        result.maxBudget_ = maxBudget_;
        if (prefMatrixBuilder_ == null) {
          result.prefMatrix_ = prefMatrix_;
        } else {
          result.prefMatrix_ = prefMatrixBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo) {
          return mergeFrom((com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo other) {
        if (other == com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getOrigin().isEmpty()) {
          origin_ = other.origin_;
          onChanged();
        }
        if (other.getMinBudget() != 0F) {
          setMinBudget(other.getMinBudget());
        }
        if (other.getMaxBudget() != 0F) {
          setMaxBudget(other.getMaxBudget());
        }
        if (other.hasPrefMatrix()) {
          mergePrefMatrix(other.getPrefMatrix());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object origin_ = "";
      /**
       * <code>optional string origin = 2;</code>
       */
      public java.lang.String getOrigin() {
        java.lang.Object ref = origin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          origin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string origin = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOriginBytes() {
        java.lang.Object ref = origin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          origin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string origin = 2;</code>
       */
      public Builder setOrigin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string origin = 2;</code>
       */
      public Builder clearOrigin() {
        
        origin_ = getDefaultInstance().getOrigin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string origin = 2;</code>
       */
      public Builder setOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        origin_ = value;
        onChanged();
        return this;
      }

      private float minBudget_ ;
      /**
       * <code>optional float minBudget = 3;</code>
       */
      public float getMinBudget() {
        return minBudget_;
      }
      /**
       * <code>optional float minBudget = 3;</code>
       */
      public Builder setMinBudget(float value) {
        
        minBudget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float minBudget = 3;</code>
       */
      public Builder clearMinBudget() {
        
        minBudget_ = 0F;
        onChanged();
        return this;
      }

      private float maxBudget_ ;
      /**
       * <code>optional float maxBudget = 4;</code>
       */
      public float getMaxBudget() {
        return maxBudget_;
      }
      /**
       * <code>optional float maxBudget = 4;</code>
       */
      public Builder setMaxBudget(float value) {
        
        maxBudget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float maxBudget = 4;</code>
       */
      public Builder clearMaxBudget() {
        
        maxBudget_ = 0F;
        onChanged();
        return this;
      }

      private com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref prefMatrix_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder> prefMatrixBuilder_;
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public boolean hasPrefMatrix() {
        return prefMatrixBuilder_ != null || prefMatrix_ != null;
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getPrefMatrix() {
        if (prefMatrixBuilder_ == null) {
          return prefMatrix_ == null ? com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.getDefaultInstance() : prefMatrix_;
        } else {
          return prefMatrixBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public Builder setPrefMatrix(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref value) {
        if (prefMatrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prefMatrix_ = value;
          onChanged();
        } else {
          prefMatrixBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public Builder setPrefMatrix(
          com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder builderForValue) {
        if (prefMatrixBuilder_ == null) {
          prefMatrix_ = builderForValue.build();
          onChanged();
        } else {
          prefMatrixBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public Builder mergePrefMatrix(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref value) {
        if (prefMatrixBuilder_ == null) {
          if (prefMatrix_ != null) {
            prefMatrix_ =
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.newBuilder(prefMatrix_).mergeFrom(value).buildPartial();
          } else {
            prefMatrix_ = value;
          }
          onChanged();
        } else {
          prefMatrixBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public Builder clearPrefMatrix() {
        if (prefMatrixBuilder_ == null) {
          prefMatrix_ = null;
          onChanged();
        } else {
          prefMatrix_ = null;
          prefMatrixBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder getPrefMatrixBuilder() {
        
        onChanged();
        return getPrefMatrixFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder getPrefMatrixOrBuilder() {
        if (prefMatrixBuilder_ != null) {
          return prefMatrixBuilder_.getMessageOrBuilder();
        } else {
          return prefMatrix_ == null ?
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.getDefaultInstance() : prefMatrix_;
        }
      }
      /**
       * <code>optional .user.UserPref prefMatrix = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder> 
          getPrefMatrixFieldBuilder() {
        if (prefMatrixBuilder_ == null) {
          prefMatrixBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder>(
                  getPrefMatrix(),
                  getParentForChildren(),
                  isClean());
          prefMatrix_ = null;
        }
        return prefMatrixBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:user.UserInfo)
    private static final com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo();
    }

    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserPrefOrBuilder extends
      // @@protoc_insertion_point(interface_extends:user.UserPref)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool artsy = 1;</code>
     */
    boolean getArtsy();

    /**
     * <code>optional bool adrenaline = 2;</code>
     */
    boolean getAdrenaline();

    /**
     * <code>optional bool backpacker = 3;</code>
     */
    boolean getBackpacker();

    /**
     * <code>optional bool beach = 4;</code>
     */
    boolean getBeach();

    /**
     * <code>optional bool budget = 5;</code>
     */
    boolean getBudget();

    /**
     * <code>optional bool family = 6;</code>
     */
    boolean getFamily();

    /**
     * <code>optional bool foodie = 7;</code>
     */
    boolean getFoodie();

    /**
     * <code>optional bool green = 8;</code>
     */
    boolean getGreen();

    /**
     * <code>optional bool history = 9;</code>
     */
    boolean getHistory();

    /**
     * <code>optional bool local = 10;</code>
     */
    boolean getLocal();

    /**
     * <code>optional bool luxury = 11;</code>
     */
    boolean getLuxury();

    /**
     * <code>optional bool nature = 12;</code>
     */
    boolean getNature();

    /**
     * <code>optional bool nightlife = 13;</code>
     */
    boolean getNightlife();

    /**
     * <code>optional bool serene = 14;</code>
     */
    boolean getSerene();

    /**
     * <code>optional bool shopping = 15;</code>
     */
    boolean getShopping();

    /**
     * <code>optional bool student = 16;</code>
     */
    boolean getStudent();

    /**
     * <code>optional bool trendsetter = 17;</code>
     */
    boolean getTrendsetter();

    /**
     * <code>optional bool urban = 18;</code>
     */
    boolean getUrban();

    /**
     * <code>optional bool vegetarian = 19;</code>
     */
    boolean getVegetarian();
  }
  /**
   * Protobuf type {@code user.UserPref}
   */
  public  static final class UserPref extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:user.UserPref)
      UserPrefOrBuilder {
    // Use UserPref.newBuilder() to construct.
    private UserPref(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserPref() {
      artsy_ = false;
      adrenaline_ = false;
      backpacker_ = false;
      beach_ = false;
      budget_ = false;
      family_ = false;
      foodie_ = false;
      green_ = false;
      history_ = false;
      local_ = false;
      luxury_ = false;
      nature_ = false;
      nightlife_ = false;
      serene_ = false;
      shopping_ = false;
      student_ = false;
      trendsetter_ = false;
      urban_ = false;
      vegetarian_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserPref(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              artsy_ = input.readBool();
              break;
            }
            case 16: {

              adrenaline_ = input.readBool();
              break;
            }
            case 24: {

              backpacker_ = input.readBool();
              break;
            }
            case 32: {

              beach_ = input.readBool();
              break;
            }
            case 40: {

              budget_ = input.readBool();
              break;
            }
            case 48: {

              family_ = input.readBool();
              break;
            }
            case 56: {

              foodie_ = input.readBool();
              break;
            }
            case 64: {

              green_ = input.readBool();
              break;
            }
            case 72: {

              history_ = input.readBool();
              break;
            }
            case 80: {

              local_ = input.readBool();
              break;
            }
            case 88: {

              luxury_ = input.readBool();
              break;
            }
            case 96: {

              nature_ = input.readBool();
              break;
            }
            case 104: {

              nightlife_ = input.readBool();
              break;
            }
            case 112: {

              serene_ = input.readBool();
              break;
            }
            case 120: {

              shopping_ = input.readBool();
              break;
            }
            case 128: {

              student_ = input.readBool();
              break;
            }
            case 136: {

              trendsetter_ = input.readBool();
              break;
            }
            case 144: {

              urban_ = input.readBool();
              break;
            }
            case 152: {

              vegetarian_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserPref_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserPref_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.class, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder.class);
    }

    public static final int ARTSY_FIELD_NUMBER = 1;
    private boolean artsy_;
    /**
     * <code>optional bool artsy = 1;</code>
     */
    public boolean getArtsy() {
      return artsy_;
    }

    public static final int ADRENALINE_FIELD_NUMBER = 2;
    private boolean adrenaline_;
    /**
     * <code>optional bool adrenaline = 2;</code>
     */
    public boolean getAdrenaline() {
      return adrenaline_;
    }

    public static final int BACKPACKER_FIELD_NUMBER = 3;
    private boolean backpacker_;
    /**
     * <code>optional bool backpacker = 3;</code>
     */
    public boolean getBackpacker() {
      return backpacker_;
    }

    public static final int BEACH_FIELD_NUMBER = 4;
    private boolean beach_;
    /**
     * <code>optional bool beach = 4;</code>
     */
    public boolean getBeach() {
      return beach_;
    }

    public static final int BUDGET_FIELD_NUMBER = 5;
    private boolean budget_;
    /**
     * <code>optional bool budget = 5;</code>
     */
    public boolean getBudget() {
      return budget_;
    }

    public static final int FAMILY_FIELD_NUMBER = 6;
    private boolean family_;
    /**
     * <code>optional bool family = 6;</code>
     */
    public boolean getFamily() {
      return family_;
    }

    public static final int FOODIE_FIELD_NUMBER = 7;
    private boolean foodie_;
    /**
     * <code>optional bool foodie = 7;</code>
     */
    public boolean getFoodie() {
      return foodie_;
    }

    public static final int GREEN_FIELD_NUMBER = 8;
    private boolean green_;
    /**
     * <code>optional bool green = 8;</code>
     */
    public boolean getGreen() {
      return green_;
    }

    public static final int HISTORY_FIELD_NUMBER = 9;
    private boolean history_;
    /**
     * <code>optional bool history = 9;</code>
     */
    public boolean getHistory() {
      return history_;
    }

    public static final int LOCAL_FIELD_NUMBER = 10;
    private boolean local_;
    /**
     * <code>optional bool local = 10;</code>
     */
    public boolean getLocal() {
      return local_;
    }

    public static final int LUXURY_FIELD_NUMBER = 11;
    private boolean luxury_;
    /**
     * <code>optional bool luxury = 11;</code>
     */
    public boolean getLuxury() {
      return luxury_;
    }

    public static final int NATURE_FIELD_NUMBER = 12;
    private boolean nature_;
    /**
     * <code>optional bool nature = 12;</code>
     */
    public boolean getNature() {
      return nature_;
    }

    public static final int NIGHTLIFE_FIELD_NUMBER = 13;
    private boolean nightlife_;
    /**
     * <code>optional bool nightlife = 13;</code>
     */
    public boolean getNightlife() {
      return nightlife_;
    }

    public static final int SERENE_FIELD_NUMBER = 14;
    private boolean serene_;
    /**
     * <code>optional bool serene = 14;</code>
     */
    public boolean getSerene() {
      return serene_;
    }

    public static final int SHOPPING_FIELD_NUMBER = 15;
    private boolean shopping_;
    /**
     * <code>optional bool shopping = 15;</code>
     */
    public boolean getShopping() {
      return shopping_;
    }

    public static final int STUDENT_FIELD_NUMBER = 16;
    private boolean student_;
    /**
     * <code>optional bool student = 16;</code>
     */
    public boolean getStudent() {
      return student_;
    }

    public static final int TRENDSETTER_FIELD_NUMBER = 17;
    private boolean trendsetter_;
    /**
     * <code>optional bool trendsetter = 17;</code>
     */
    public boolean getTrendsetter() {
      return trendsetter_;
    }

    public static final int URBAN_FIELD_NUMBER = 18;
    private boolean urban_;
    /**
     * <code>optional bool urban = 18;</code>
     */
    public boolean getUrban() {
      return urban_;
    }

    public static final int VEGETARIAN_FIELD_NUMBER = 19;
    private boolean vegetarian_;
    /**
     * <code>optional bool vegetarian = 19;</code>
     */
    public boolean getVegetarian() {
      return vegetarian_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (artsy_ != false) {
        output.writeBool(1, artsy_);
      }
      if (adrenaline_ != false) {
        output.writeBool(2, adrenaline_);
      }
      if (backpacker_ != false) {
        output.writeBool(3, backpacker_);
      }
      if (beach_ != false) {
        output.writeBool(4, beach_);
      }
      if (budget_ != false) {
        output.writeBool(5, budget_);
      }
      if (family_ != false) {
        output.writeBool(6, family_);
      }
      if (foodie_ != false) {
        output.writeBool(7, foodie_);
      }
      if (green_ != false) {
        output.writeBool(8, green_);
      }
      if (history_ != false) {
        output.writeBool(9, history_);
      }
      if (local_ != false) {
        output.writeBool(10, local_);
      }
      if (luxury_ != false) {
        output.writeBool(11, luxury_);
      }
      if (nature_ != false) {
        output.writeBool(12, nature_);
      }
      if (nightlife_ != false) {
        output.writeBool(13, nightlife_);
      }
      if (serene_ != false) {
        output.writeBool(14, serene_);
      }
      if (shopping_ != false) {
        output.writeBool(15, shopping_);
      }
      if (student_ != false) {
        output.writeBool(16, student_);
      }
      if (trendsetter_ != false) {
        output.writeBool(17, trendsetter_);
      }
      if (urban_ != false) {
        output.writeBool(18, urban_);
      }
      if (vegetarian_ != false) {
        output.writeBool(19, vegetarian_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (artsy_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, artsy_);
      }
      if (adrenaline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, adrenaline_);
      }
      if (backpacker_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, backpacker_);
      }
      if (beach_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, beach_);
      }
      if (budget_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, budget_);
      }
      if (family_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, family_);
      }
      if (foodie_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, foodie_);
      }
      if (green_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, green_);
      }
      if (history_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, history_);
      }
      if (local_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, local_);
      }
      if (luxury_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, luxury_);
      }
      if (nature_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, nature_);
      }
      if (nightlife_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, nightlife_);
      }
      if (serene_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, serene_);
      }
      if (shopping_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, shopping_);
      }
      if (student_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, student_);
      }
      if (trendsetter_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, trendsetter_);
      }
      if (urban_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(18, urban_);
      }
      if (vegetarian_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, vegetarian_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code user.UserPref}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:user.UserPref)
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPrefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserPref_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserPref_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.class, com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.Builder.class);
      }

      // Construct using com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        artsy_ = false;

        adrenaline_ = false;

        backpacker_ = false;

        beach_ = false;

        budget_ = false;

        family_ = false;

        foodie_ = false;

        green_ = false;

        history_ = false;

        local_ = false;

        luxury_ = false;

        nature_ = false;

        nightlife_ = false;

        serene_ = false;

        shopping_ = false;

        student_ = false;

        trendsetter_ = false;

        urban_ = false;

        vegetarian_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.internal_static_user_UserPref_descriptor;
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getDefaultInstanceForType() {
        return com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.getDefaultInstance();
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref build() {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref buildPartial() {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref result = new com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref(this);
        result.artsy_ = artsy_;
        result.adrenaline_ = adrenaline_;
        result.backpacker_ = backpacker_;
        result.beach_ = beach_;
        result.budget_ = budget_;
        result.family_ = family_;
        result.foodie_ = foodie_;
        result.green_ = green_;
        result.history_ = history_;
        result.local_ = local_;
        result.luxury_ = luxury_;
        result.nature_ = nature_;
        result.nightlife_ = nightlife_;
        result.serene_ = serene_;
        result.shopping_ = shopping_;
        result.student_ = student_;
        result.trendsetter_ = trendsetter_;
        result.urban_ = urban_;
        result.vegetarian_ = vegetarian_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref) {
          return mergeFrom((com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref other) {
        if (other == com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref.getDefaultInstance()) return this;
        if (other.getArtsy() != false) {
          setArtsy(other.getArtsy());
        }
        if (other.getAdrenaline() != false) {
          setAdrenaline(other.getAdrenaline());
        }
        if (other.getBackpacker() != false) {
          setBackpacker(other.getBackpacker());
        }
        if (other.getBeach() != false) {
          setBeach(other.getBeach());
        }
        if (other.getBudget() != false) {
          setBudget(other.getBudget());
        }
        if (other.getFamily() != false) {
          setFamily(other.getFamily());
        }
        if (other.getFoodie() != false) {
          setFoodie(other.getFoodie());
        }
        if (other.getGreen() != false) {
          setGreen(other.getGreen());
        }
        if (other.getHistory() != false) {
          setHistory(other.getHistory());
        }
        if (other.getLocal() != false) {
          setLocal(other.getLocal());
        }
        if (other.getLuxury() != false) {
          setLuxury(other.getLuxury());
        }
        if (other.getNature() != false) {
          setNature(other.getNature());
        }
        if (other.getNightlife() != false) {
          setNightlife(other.getNightlife());
        }
        if (other.getSerene() != false) {
          setSerene(other.getSerene());
        }
        if (other.getShopping() != false) {
          setShopping(other.getShopping());
        }
        if (other.getStudent() != false) {
          setStudent(other.getStudent());
        }
        if (other.getTrendsetter() != false) {
          setTrendsetter(other.getTrendsetter());
        }
        if (other.getUrban() != false) {
          setUrban(other.getUrban());
        }
        if (other.getVegetarian() != false) {
          setVegetarian(other.getVegetarian());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean artsy_ ;
      /**
       * <code>optional bool artsy = 1;</code>
       */
      public boolean getArtsy() {
        return artsy_;
      }
      /**
       * <code>optional bool artsy = 1;</code>
       */
      public Builder setArtsy(boolean value) {
        
        artsy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool artsy = 1;</code>
       */
      public Builder clearArtsy() {
        
        artsy_ = false;
        onChanged();
        return this;
      }

      private boolean adrenaline_ ;
      /**
       * <code>optional bool adrenaline = 2;</code>
       */
      public boolean getAdrenaline() {
        return adrenaline_;
      }
      /**
       * <code>optional bool adrenaline = 2;</code>
       */
      public Builder setAdrenaline(boolean value) {
        
        adrenaline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool adrenaline = 2;</code>
       */
      public Builder clearAdrenaline() {
        
        adrenaline_ = false;
        onChanged();
        return this;
      }

      private boolean backpacker_ ;
      /**
       * <code>optional bool backpacker = 3;</code>
       */
      public boolean getBackpacker() {
        return backpacker_;
      }
      /**
       * <code>optional bool backpacker = 3;</code>
       */
      public Builder setBackpacker(boolean value) {
        
        backpacker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool backpacker = 3;</code>
       */
      public Builder clearBackpacker() {
        
        backpacker_ = false;
        onChanged();
        return this;
      }

      private boolean beach_ ;
      /**
       * <code>optional bool beach = 4;</code>
       */
      public boolean getBeach() {
        return beach_;
      }
      /**
       * <code>optional bool beach = 4;</code>
       */
      public Builder setBeach(boolean value) {
        
        beach_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool beach = 4;</code>
       */
      public Builder clearBeach() {
        
        beach_ = false;
        onChanged();
        return this;
      }

      private boolean budget_ ;
      /**
       * <code>optional bool budget = 5;</code>
       */
      public boolean getBudget() {
        return budget_;
      }
      /**
       * <code>optional bool budget = 5;</code>
       */
      public Builder setBudget(boolean value) {
        
        budget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool budget = 5;</code>
       */
      public Builder clearBudget() {
        
        budget_ = false;
        onChanged();
        return this;
      }

      private boolean family_ ;
      /**
       * <code>optional bool family = 6;</code>
       */
      public boolean getFamily() {
        return family_;
      }
      /**
       * <code>optional bool family = 6;</code>
       */
      public Builder setFamily(boolean value) {
        
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool family = 6;</code>
       */
      public Builder clearFamily() {
        
        family_ = false;
        onChanged();
        return this;
      }

      private boolean foodie_ ;
      /**
       * <code>optional bool foodie = 7;</code>
       */
      public boolean getFoodie() {
        return foodie_;
      }
      /**
       * <code>optional bool foodie = 7;</code>
       */
      public Builder setFoodie(boolean value) {
        
        foodie_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool foodie = 7;</code>
       */
      public Builder clearFoodie() {
        
        foodie_ = false;
        onChanged();
        return this;
      }

      private boolean green_ ;
      /**
       * <code>optional bool green = 8;</code>
       */
      public boolean getGreen() {
        return green_;
      }
      /**
       * <code>optional bool green = 8;</code>
       */
      public Builder setGreen(boolean value) {
        
        green_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool green = 8;</code>
       */
      public Builder clearGreen() {
        
        green_ = false;
        onChanged();
        return this;
      }

      private boolean history_ ;
      /**
       * <code>optional bool history = 9;</code>
       */
      public boolean getHistory() {
        return history_;
      }
      /**
       * <code>optional bool history = 9;</code>
       */
      public Builder setHistory(boolean value) {
        
        history_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool history = 9;</code>
       */
      public Builder clearHistory() {
        
        history_ = false;
        onChanged();
        return this;
      }

      private boolean local_ ;
      /**
       * <code>optional bool local = 10;</code>
       */
      public boolean getLocal() {
        return local_;
      }
      /**
       * <code>optional bool local = 10;</code>
       */
      public Builder setLocal(boolean value) {
        
        local_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool local = 10;</code>
       */
      public Builder clearLocal() {
        
        local_ = false;
        onChanged();
        return this;
      }

      private boolean luxury_ ;
      /**
       * <code>optional bool luxury = 11;</code>
       */
      public boolean getLuxury() {
        return luxury_;
      }
      /**
       * <code>optional bool luxury = 11;</code>
       */
      public Builder setLuxury(boolean value) {
        
        luxury_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool luxury = 11;</code>
       */
      public Builder clearLuxury() {
        
        luxury_ = false;
        onChanged();
        return this;
      }

      private boolean nature_ ;
      /**
       * <code>optional bool nature = 12;</code>
       */
      public boolean getNature() {
        return nature_;
      }
      /**
       * <code>optional bool nature = 12;</code>
       */
      public Builder setNature(boolean value) {
        
        nature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool nature = 12;</code>
       */
      public Builder clearNature() {
        
        nature_ = false;
        onChanged();
        return this;
      }

      private boolean nightlife_ ;
      /**
       * <code>optional bool nightlife = 13;</code>
       */
      public boolean getNightlife() {
        return nightlife_;
      }
      /**
       * <code>optional bool nightlife = 13;</code>
       */
      public Builder setNightlife(boolean value) {
        
        nightlife_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool nightlife = 13;</code>
       */
      public Builder clearNightlife() {
        
        nightlife_ = false;
        onChanged();
        return this;
      }

      private boolean serene_ ;
      /**
       * <code>optional bool serene = 14;</code>
       */
      public boolean getSerene() {
        return serene_;
      }
      /**
       * <code>optional bool serene = 14;</code>
       */
      public Builder setSerene(boolean value) {
        
        serene_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool serene = 14;</code>
       */
      public Builder clearSerene() {
        
        serene_ = false;
        onChanged();
        return this;
      }

      private boolean shopping_ ;
      /**
       * <code>optional bool shopping = 15;</code>
       */
      public boolean getShopping() {
        return shopping_;
      }
      /**
       * <code>optional bool shopping = 15;</code>
       */
      public Builder setShopping(boolean value) {
        
        shopping_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool shopping = 15;</code>
       */
      public Builder clearShopping() {
        
        shopping_ = false;
        onChanged();
        return this;
      }

      private boolean student_ ;
      /**
       * <code>optional bool student = 16;</code>
       */
      public boolean getStudent() {
        return student_;
      }
      /**
       * <code>optional bool student = 16;</code>
       */
      public Builder setStudent(boolean value) {
        
        student_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool student = 16;</code>
       */
      public Builder clearStudent() {
        
        student_ = false;
        onChanged();
        return this;
      }

      private boolean trendsetter_ ;
      /**
       * <code>optional bool trendsetter = 17;</code>
       */
      public boolean getTrendsetter() {
        return trendsetter_;
      }
      /**
       * <code>optional bool trendsetter = 17;</code>
       */
      public Builder setTrendsetter(boolean value) {
        
        trendsetter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool trendsetter = 17;</code>
       */
      public Builder clearTrendsetter() {
        
        trendsetter_ = false;
        onChanged();
        return this;
      }

      private boolean urban_ ;
      /**
       * <code>optional bool urban = 18;</code>
       */
      public boolean getUrban() {
        return urban_;
      }
      /**
       * <code>optional bool urban = 18;</code>
       */
      public Builder setUrban(boolean value) {
        
        urban_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool urban = 18;</code>
       */
      public Builder clearUrban() {
        
        urban_ = false;
        onChanged();
        return this;
      }

      private boolean vegetarian_ ;
      /**
       * <code>optional bool vegetarian = 19;</code>
       */
      public boolean getVegetarian() {
        return vegetarian_;
      }
      /**
       * <code>optional bool vegetarian = 19;</code>
       */
      public Builder setVegetarian(boolean value) {
        
        vegetarian_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool vegetarian = 19;</code>
       */
      public Builder clearVegetarian() {
        
        vegetarian_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:user.UserPref)
    }

    // @@protoc_insertion_point(class_scope:user.UserPref)
    private static final com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref();
    }

    public static com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserPref>
        PARSER = new com.google.protobuf.AbstractParser<UserPref>() {
      public UserPref parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserPref(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserPref> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserPref> getParserForType() {
      return PARSER;
    }

    public com.expedia.www.packagefinder.database.user.UserInfoProtos.UserPref getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_UserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserPref_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_UserPref_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016userinfo.proto\022\004user\"t\n\010UserInfo\022\016\n\006us" +
      "erId\030\001 \001(\t\022\016\n\006origin\030\002 \001(\t\022\021\n\tminBudget\030" +
      "\003 \001(\002\022\021\n\tmaxBudget\030\004 \001(\002\022\"\n\nprefMatrix\030\005" +
      " \001(\0132\016.user.UserPref\"\315\002\n\010UserPref\022\r\n\005art" +
      "sy\030\001 \001(\010\022\022\n\nadrenaline\030\002 \001(\010\022\022\n\nbackpack" +
      "er\030\003 \001(\010\022\r\n\005beach\030\004 \001(\010\022\016\n\006budget\030\005 \001(\010\022" +
      "\016\n\006family\030\006 \001(\010\022\016\n\006foodie\030\007 \001(\010\022\r\n\005green" +
      "\030\010 \001(\010\022\017\n\007history\030\t \001(\010\022\r\n\005local\030\n \001(\010\022\016" +
      "\n\006luxury\030\013 \001(\010\022\016\n\006nature\030\014 \001(\010\022\021\n\tnightl" +
      "ife\030\r \001(\010\022\016\n\006serene\030\016 \001(\010\022\020\n\010shopping\030\017 ",
      "\001(\010\022\017\n\007student\030\020 \001(\010\022\023\n\013trendsetter\030\021 \001(" +
      "\010\022\r\n\005urban\030\022 \001(\010\022\022\n\nvegetarian\030\023 \001(\010B=\n+" +
      "com.expedia.www.packagefinder.database.u" +
      "serB\016UserInfoProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_UserInfo_descriptor,
        new java.lang.String[] { "UserId", "Origin", "MinBudget", "MaxBudget", "PrefMatrix", });
    internal_static_user_UserPref_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserPref_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_UserPref_descriptor,
        new java.lang.String[] { "Artsy", "Adrenaline", "Backpacker", "Beach", "Budget", "Family", "Foodie", "Green", "History", "Local", "Luxury", "Nature", "Nightlife", "Serene", "Shopping", "Student", "Trendsetter", "Urban", "Vegetarian", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
