// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotels.proto

package com.expedia.www.packagefinder.database.hotel;

public final class HotelProtos {
  private HotelProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HotelsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hotel.Hotels)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> 
        getHotelList();
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getHotel(int index);
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    int getHotelCount();
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    java.util.List<? extends com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder> 
        getHotelOrBuilderList();
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder getHotelOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hotel.Hotels}
   */
  public  static final class Hotels extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hotel.Hotels)
      HotelsOrBuilder {
    // Use Hotels.newBuilder() to construct.
    private Hotels(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Hotels() {
      hotel_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Hotels(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                hotel_ = new java.util.ArrayList<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel>();
                mutable_bitField0_ |= 0x00000001;
              }
              hotel_.add(input.readMessage(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          hotel_ = java.util.Collections.unmodifiableList(hotel_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotels_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotels_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.class, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.Builder.class);
    }

    public static final int HOTEL_FIELD_NUMBER = 1;
    private java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> hotel_;
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    public java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> getHotelList() {
      return hotel_;
    }
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    public java.util.List<? extends com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder> 
        getHotelOrBuilderList() {
      return hotel_;
    }
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    public int getHotelCount() {
      return hotel_.size();
    }
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getHotel(int index) {
      return hotel_.get(index);
    }
    /**
     * <code>repeated .hotel.Hotel hotel = 1;</code>
     */
    public com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder getHotelOrBuilder(
        int index) {
      return hotel_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hotel_.size(); i++) {
        output.writeMessage(1, hotel_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hotel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hotel_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hotel.Hotels}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hotel.Hotels)
        com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotels_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotels_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.class, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.Builder.class);
      }

      // Construct using com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHotelFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (hotelBuilder_ == null) {
          hotel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          hotelBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotels_descriptor;
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels getDefaultInstanceForType() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.getDefaultInstance();
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels build() {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels buildPartial() {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels result = new com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels(this);
        int from_bitField0_ = bitField0_;
        if (hotelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            hotel_ = java.util.Collections.unmodifiableList(hotel_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hotel_ = hotel_;
        } else {
          result.hotel_ = hotelBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels) {
          return mergeFrom((com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels other) {
        if (other == com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels.getDefaultInstance()) return this;
        if (hotelBuilder_ == null) {
          if (!other.hotel_.isEmpty()) {
            if (hotel_.isEmpty()) {
              hotel_ = other.hotel_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHotelIsMutable();
              hotel_.addAll(other.hotel_);
            }
            onChanged();
          }
        } else {
          if (!other.hotel_.isEmpty()) {
            if (hotelBuilder_.isEmpty()) {
              hotelBuilder_.dispose();
              hotelBuilder_ = null;
              hotel_ = other.hotel_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hotelBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHotelFieldBuilder() : null;
            } else {
              hotelBuilder_.addAllMessages(other.hotel_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> hotel_ =
        java.util.Collections.emptyList();
      private void ensureHotelIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          hotel_ = new java.util.ArrayList<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel>(hotel_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder, com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder> hotelBuilder_;

      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> getHotelList() {
        if (hotelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hotel_);
        } else {
          return hotelBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public int getHotelCount() {
        if (hotelBuilder_ == null) {
          return hotel_.size();
        } else {
          return hotelBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getHotel(int index) {
        if (hotelBuilder_ == null) {
          return hotel_.get(index);
        } else {
          return hotelBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder setHotel(
          int index, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel value) {
        if (hotelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHotelIsMutable();
          hotel_.set(index, value);
          onChanged();
        } else {
          hotelBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder setHotel(
          int index, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder builderForValue) {
        if (hotelBuilder_ == null) {
          ensureHotelIsMutable();
          hotel_.set(index, builderForValue.build());
          onChanged();
        } else {
          hotelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder addHotel(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel value) {
        if (hotelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHotelIsMutable();
          hotel_.add(value);
          onChanged();
        } else {
          hotelBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder addHotel(
          int index, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel value) {
        if (hotelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHotelIsMutable();
          hotel_.add(index, value);
          onChanged();
        } else {
          hotelBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder addHotel(
          com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder builderForValue) {
        if (hotelBuilder_ == null) {
          ensureHotelIsMutable();
          hotel_.add(builderForValue.build());
          onChanged();
        } else {
          hotelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder addHotel(
          int index, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder builderForValue) {
        if (hotelBuilder_ == null) {
          ensureHotelIsMutable();
          hotel_.add(index, builderForValue.build());
          onChanged();
        } else {
          hotelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder addAllHotel(
          java.lang.Iterable<? extends com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel> values) {
        if (hotelBuilder_ == null) {
          ensureHotelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hotel_);
          onChanged();
        } else {
          hotelBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder clearHotel() {
        if (hotelBuilder_ == null) {
          hotel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hotelBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public Builder removeHotel(int index) {
        if (hotelBuilder_ == null) {
          ensureHotelIsMutable();
          hotel_.remove(index);
          onChanged();
        } else {
          hotelBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder getHotelBuilder(
          int index) {
        return getHotelFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder getHotelOrBuilder(
          int index) {
        if (hotelBuilder_ == null) {
          return hotel_.get(index);  } else {
          return hotelBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public java.util.List<? extends com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder> 
           getHotelOrBuilderList() {
        if (hotelBuilder_ != null) {
          return hotelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hotel_);
        }
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder addHotelBuilder() {
        return getHotelFieldBuilder().addBuilder(
            com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.getDefaultInstance());
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder addHotelBuilder(
          int index) {
        return getHotelFieldBuilder().addBuilder(
            index, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.getDefaultInstance());
      }
      /**
       * <code>repeated .hotel.Hotel hotel = 1;</code>
       */
      public java.util.List<com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder> 
           getHotelBuilderList() {
        return getHotelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder, com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder> 
          getHotelFieldBuilder() {
        if (hotelBuilder_ == null) {
          hotelBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder, com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder>(
                  hotel_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          hotel_ = null;
        }
        return hotelBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hotel.Hotels)
    }

    // @@protoc_insertion_point(class_scope:hotel.Hotels)
    private static final com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels();
    }

    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hotels>
        PARSER = new com.google.protobuf.AbstractParser<Hotels>() {
      public Hotels parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Hotels(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hotels> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hotels> getParserForType() {
      return PARSER;
    }

    public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotels getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HotelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hotel.Hotel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string hotelId = 1;</code>
     */
    java.lang.String getHotelId();
    /**
     * <code>optional string hotelId = 1;</code>
     */
    com.google.protobuf.ByteString
        getHotelIdBytes();

    /**
     * <code>optional float hotelScore = 2;</code>
     */
    float getHotelScore();

    /**
     * <code>optional int32 hotelRank = 3;</code>
     */
    int getHotelRank();
  }
  /**
   * Protobuf type {@code hotel.Hotel}
   */
  public  static final class Hotel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hotel.Hotel)
      HotelOrBuilder {
    // Use Hotel.newBuilder() to construct.
    private Hotel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Hotel() {
      hotelId_ = "";
      hotelScore_ = 0F;
      hotelRank_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Hotel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hotelId_ = s;
              break;
            }
            case 21: {

              hotelScore_ = input.readFloat();
              break;
            }
            case 24: {

              hotelRank_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.class, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder.class);
    }

    public static final int HOTELID_FIELD_NUMBER = 1;
    private volatile java.lang.Object hotelId_;
    /**
     * <code>optional string hotelId = 1;</code>
     */
    public java.lang.String getHotelId() {
      java.lang.Object ref = hotelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hotelId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hotelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHotelIdBytes() {
      java.lang.Object ref = hotelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hotelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOTELSCORE_FIELD_NUMBER = 2;
    private float hotelScore_;
    /**
     * <code>optional float hotelScore = 2;</code>
     */
    public float getHotelScore() {
      return hotelScore_;
    }

    public static final int HOTELRANK_FIELD_NUMBER = 3;
    private int hotelRank_;
    /**
     * <code>optional int32 hotelRank = 3;</code>
     */
    public int getHotelRank() {
      return hotelRank_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHotelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, hotelId_);
      }
      if (hotelScore_ != 0F) {
        output.writeFloat(2, hotelScore_);
      }
      if (hotelRank_ != 0) {
        output.writeInt32(3, hotelRank_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHotelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, hotelId_);
      }
      if (hotelScore_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, hotelScore_);
      }
      if (hotelRank_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hotelRank_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hotel.Hotel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hotel.Hotel)
        com.expedia.www.packagefinder.database.hotel.HotelProtos.HotelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.class, com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.Builder.class);
      }

      // Construct using com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hotelId_ = "";

        hotelScore_ = 0F;

        hotelRank_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.internal_static_hotel_Hotel_descriptor;
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getDefaultInstanceForType() {
        return com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.getDefaultInstance();
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel build() {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel buildPartial() {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel result = new com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel(this);
        result.hotelId_ = hotelId_;
        result.hotelScore_ = hotelScore_;
        result.hotelRank_ = hotelRank_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel) {
          return mergeFrom((com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel other) {
        if (other == com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel.getDefaultInstance()) return this;
        if (!other.getHotelId().isEmpty()) {
          hotelId_ = other.hotelId_;
          onChanged();
        }
        if (other.getHotelScore() != 0F) {
          setHotelScore(other.getHotelScore());
        }
        if (other.getHotelRank() != 0) {
          setHotelRank(other.getHotelRank());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hotelId_ = "";
      /**
       * <code>optional string hotelId = 1;</code>
       */
      public java.lang.String getHotelId() {
        java.lang.Object ref = hotelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hotelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hotelId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHotelIdBytes() {
        java.lang.Object ref = hotelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hotelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hotelId = 1;</code>
       */
      public Builder setHotelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hotelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hotelId = 1;</code>
       */
      public Builder clearHotelId() {
        
        hotelId_ = getDefaultInstance().getHotelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hotelId = 1;</code>
       */
      public Builder setHotelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hotelId_ = value;
        onChanged();
        return this;
      }

      private float hotelScore_ ;
      /**
       * <code>optional float hotelScore = 2;</code>
       */
      public float getHotelScore() {
        return hotelScore_;
      }
      /**
       * <code>optional float hotelScore = 2;</code>
       */
      public Builder setHotelScore(float value) {
        
        hotelScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float hotelScore = 2;</code>
       */
      public Builder clearHotelScore() {
        
        hotelScore_ = 0F;
        onChanged();
        return this;
      }

      private int hotelRank_ ;
      /**
       * <code>optional int32 hotelRank = 3;</code>
       */
      public int getHotelRank() {
        return hotelRank_;
      }
      /**
       * <code>optional int32 hotelRank = 3;</code>
       */
      public Builder setHotelRank(int value) {
        
        hotelRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hotelRank = 3;</code>
       */
      public Builder clearHotelRank() {
        
        hotelRank_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hotel.Hotel)
    }

    // @@protoc_insertion_point(class_scope:hotel.Hotel)
    private static final com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel();
    }

    public static com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hotel>
        PARSER = new com.google.protobuf.AbstractParser<Hotel>() {
      public Hotel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Hotel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hotel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hotel> getParserForType() {
      return PARSER;
    }

    public com.expedia.www.packagefinder.database.hotel.HotelProtos.Hotel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotel_Hotels_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hotel_Hotels_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hotel_Hotel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hotel_Hotel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014hotels.proto\022\005hotel\"%\n\006Hotels\022\033\n\005hotel" +
      "\030\001 \003(\0132\014.hotel.Hotel\"?\n\005Hotel\022\017\n\007hotelId" +
      "\030\001 \001(\t\022\022\n\nhotelScore\030\002 \001(\002\022\021\n\thotelRank\030" +
      "\003 \001(\005B;\n,com.expedia.www.packagefinder.d" +
      "atabase.hotelB\013HotelProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hotel_Hotels_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hotel_Hotels_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hotel_Hotels_descriptor,
        new java.lang.String[] { "Hotel", });
    internal_static_hotel_Hotel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hotel_Hotel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hotel_Hotel_descriptor,
        new java.lang.String[] { "HotelId", "HotelScore", "HotelRank", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
