# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotels.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hotels.proto',
  package='hotel',
  syntax='proto3',
  serialized_pb=_b('\n\x0chotels.proto\x12\x05hotel\"%\n\x06Hotels\x12\x1b\n\x05hotel\x18\x01 \x03(\x0b\x32\x0c.hotel.Hotel\"?\n\x05Hotel\x12\x0f\n\x07hotelId\x18\x01 \x01(\t\x12\x12\n\nhotelScore\x18\x02 \x01(\x02\x12\x11\n\thotelRank\x18\x03 \x01(\x05\x42\x32\n#com.expedia.www.packagefinder.hotelB\x0bHotelProtosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HOTELS = _descriptor.Descriptor(
  name='Hotels',
  full_name='hotel.Hotels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hotel', full_name='hotel.Hotels.hotel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=60,
)


_HOTEL = _descriptor.Descriptor(
  name='Hotel',
  full_name='hotel.Hotel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hotelId', full_name='hotel.Hotel.hotelId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hotelScore', full_name='hotel.Hotel.hotelScore', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hotelRank', full_name='hotel.Hotel.hotelRank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=125,
)

_HOTELS.fields_by_name['hotel'].message_type = _HOTEL
DESCRIPTOR.message_types_by_name['Hotels'] = _HOTELS
DESCRIPTOR.message_types_by_name['Hotel'] = _HOTEL

Hotels = _reflection.GeneratedProtocolMessageType('Hotels', (_message.Message,), dict(
  DESCRIPTOR = _HOTELS,
  __module__ = 'hotels_pb2'
  # @@protoc_insertion_point(class_scope:hotel.Hotels)
  ))
_sym_db.RegisterMessage(Hotels)

Hotel = _reflection.GeneratedProtocolMessageType('Hotel', (_message.Message,), dict(
  DESCRIPTOR = _HOTEL,
  __module__ = 'hotels_pb2'
  # @@protoc_insertion_point(class_scope:hotel.Hotel)
  ))
_sym_db.RegisterMessage(Hotel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.expedia.www.packagefinder.hotelB\013HotelProtos'))
# @@protoc_insertion_point(module_scope)
